// This file is generated by the FlutterFire CLI.
//
// If you have not yet configured your Firebase app for Flutter Web, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Then replace the values below with the ones generated for your Firebase project.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return desktop;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFc-PhF_JIr9wRznCYZvlNEV0R2C7epAc',
    appId: '1:44062756894:web:e741d09bb6f0800eff5e0f',
    messagingSenderId: '44062756894',
    projectId: 'persona-8b272',
    authDomain: 'persona-8b272.firebaseapp.com',
    storageBucket: 'persona-8b272.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvfK4-Dd6yxfT3MrQ-75BxDYwucBUUEw',
    appId: '1:44062756894:android:142a98a2063e42e6ff5e0f',
    messagingSenderId: '44062756894',
    projectId: 'persona-8b272',
    storageBucket: 'persona-8b272.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzTZcin3of08En7mB4LAIWjKXCZSkJ35Q',
    appId: '1:44062756894:ios:d4e9f726d14c9f85ff5e0f',
    messagingSenderId: '44062756894',
    projectId: 'persona-8b272',
    storageBucket: 'persona-8b272.firebasestorage.app',
    iosClientId: '44062756894-ns9c92dnuacn22khm7deekmcclcuajj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.persona',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.persona',
  );

  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
